FROM golang:1.18 AS builder

WORKDIR /app

# COPY go.mod ./
# RUN go mod download


COPY . .

RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o challenge .

FROM scratch

COPY --from=builder /app/challenge .

CMD [ "./challenge" ]